[GLOBAL]
pants_version = "2.17.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.experimental.python.packaging.pyoxidizer",
  "pants.backend.shell"
]

[python]
enable_resolves = true
interpreter_constraints = [">=3.10"]

[python-bootstrap]
search_path = [
    "<PYENV>",
    "/usr/local/bin",
    "/usr/bin",
     "<PATH>",
]

[anonymous-telemetry]
enabled = false

[source]
marker_filenames = ["SOURCE_ROOT"]

[export]
resolve = "python-default"

[black]
args = ["-l 120"]

[flake8]
args = ["--max-line-length=120"]

[isort]
args = ["-l 120", "--profile black"]

[pyoxidizer]
args = ["--release"]