AWS_REGION_MAP = {
    "us-east-2": {"name": "Ohio"},
    "us-east-1": {"name": "N. Virginia"},
    "us-west-1": {"name": "N. California"},
    "us-west-2": {"name": "Oregon"},
    "af-south-1": {"name": "Cape Town"},
    "ap-east-1": {"name": "Hong Kong"},
    "ap-south-2": {"name": "Hyderabad"},
    "ap-southeast-3": {"name": "Jakarta"},
    "ap-southeast-4": {"name": "Melbourne"},
    "ap-south-1": {"name": "Mumbai"},
    "ap-northeast-3": {"name": "Osaka"},
    "ap-northeast-2": {"name": "Seoul"},
    "ap-southeast-1": {"name": "Singapore"},
    "ap-southeast-2": {"name": "Sydney"},
    "ap-northeast-1": {"name": "Tokyo"},
    "ca-central-1": {"name": "Central"},
    "eu-central-1": {"name": "Frankfurt"},
    "eu-west-1": {"name": "Ireland"},
    "eu-west-2": {"name": "London"},
    "eu-south-1": {"name": "Milan"},
    "eu-west-3": {"name": "Paris"},
    "eu-south-2": {"name": "Spain"},
    "eu-north-1": {"name": "Stockholm"},
    "eu-central-2": {"name": "Zurich"},
    "il-central-1": {"name": "Tel Aviv"},
    "me-south-1": {"name": "Bahrain"},
    "me-central-1": {"name": "UAE"},
    "sa-east-1": {"name": "São Paulo"},
}
